test for snapshot dir

diff --git a/bin/zfs-sync-pull b/bin/zfs-sync-pull
--- a/bin/zfs-sync-pull
+++ b/bin/zfs-sync-pull
@@ -25,6 +25,11 @@ fi
 
 RECVPOOL="${3}"
 
+if [ ! -d /${DATASET}/.zfs/snapshot/ ]; then
+    echo "ERROR: ${DATASET} not mounted or has no snapshots."
+    exit 1
+fi
+
 # ALGORITHM: local_last_snapshot
 STARTAT=$( ls /${DATASET}/.zfs/snapshot/ | tail -1 )
 # ALGORITHM: ssh remote remote_last_snapshot
diff --git a/bin/zfs-sync-xz-pull b/bin/zfs-sync-xz-pull
--- a/bin/zfs-sync-xz-pull
+++ b/bin/zfs-sync-xz-pull
@@ -26,6 +26,10 @@ RECVPOOL="${3}"
 
 OUTPUTDIR="${4}"
 
+if [ ! -d /${DATASET}/.zfs/snapshot/ ]; then
+    echo "ERROR: ${DATASET} not mounted or has no snapshots."
+    exit 1
+fi
 
 # ALGORITHM: local_last_snapshot
 STARTAT=$( ls /${DATASET}/.zfs/snapshot/ | tail -1 )
diff --git a/bin/zfs-xz-multi-export b/bin/zfs-xz-multi-export
--- a/bin/zfs-xz-multi-export
+++ b/bin/zfs-xz-multi-export
@@ -18,6 +18,11 @@ if [ "x" = "x$COUNT" ]; then
     COUNT=1
 fi
 
+if [ ! -d /${DATASET}/.zfs/snapshot/ ]; then
+    echo "ERROR: ${DATASET} not mounted or has no snapshots."
+    exit 1
+fi
+
 PREVSNAP=""
 for i in $( ls /${DATASET}/.zfs/snapshot/ | grep -A${COUNT} ${STARTAT} ) ; do
 
