remove json if not mounted

diff --git a/bin/zfs-sync-xz-pull b/bin/zfs-sync-xz-pull
--- a/bin/zfs-sync-xz-pull
+++ b/bin/zfs-sync-xz-pull
@@ -26,13 +26,16 @@ RECVPOOL="${3}"
 
 OUTPUTDIR="${4}"
 
-if [ ! -d /${DATASET}/.zfs/snapshot/ ]; then
-    echo "ERROR: ${DATASET} not mounted."
-    exit 1
-fi
-
 # pattern to find when using rsync
 SAFENAME=$( echo $DATASET | tr -c '[:alnum:]' _ )
+
+if [ ! -d /${DATASET}/.zfs/snapshot/ ]; then
+    echo "ERROR: ${DATASET} not mounted."
+    if [ -e /usr/local/www/data/.snapshot.${SAFENAME}.json ]; then
+        rm  /usr/local/www/data/.snapshot.${SAFENAME}.json
+    fi
+    exit 1
+fi
 
 # ALGORITHM: local_last_snapshot
 STARTAT=$( ls /${DATASET}/.zfs/snapshot/ | tail -1 )
